# Generated by Django 3.1 on 2020-08-14 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicUserProfile',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profile_photo/')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
                ('personal_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('feedback_emails', models.BooleanField(default=False)),
                ('reminder_emails', models.BooleanField(default=False)),
                ('product_emails', models.BooleanField(default=False)),
                ('news_emails', models.BooleanField(default=False)),
                ('karma', models.IntegerField(default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
