# Generated by Django 3.1 on 2020-08-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicuserprofile',
            name='location',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
