# Generated by Django 3.1 on 2020-09-09 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_language_explore', '0003_coursestatusupdate_title'),
        ('teacher_authentication', '0004_teacheruserprofile_teacher_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherForumPost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('post_title', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.TextField(blank=True, max_length=10000, null=True)),
                ('karma', models.IntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_language_explore.teacherlanguagecourse')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_authentication.teacheruserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherForumComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('karma', models.IntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_forum.teacherforumpost')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_authentication.teacheruserprofile')),
            ],
        ),
    ]
