# Generated by Django 3.1 on 2020-09-09 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherforumcomment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_forum.teacherforumpost'),
        ),
    ]
