# Generated by Django 3.1 on 2020-08-17 10:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flag_photo/basic/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('basic_user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
                ('langauge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_language_explore.language')),
            ],
        ),
    ]
