# Generated by Django 3.1 on 2020-08-17 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0001_initial'),
        ('basic_language_explore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='basic_user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile'),
        ),
    ]
