# Generated by Django 3.1 on 2020-09-17 06:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_language_explore', '0002_auto_20200817_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicLanguageCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('course_language', models.CharField(max_length=300)),
                ('course_speakers_language', models.CharField(max_length=300)),
                ('about_language', models.TextField(default='...')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_language_explore.basiclanguagecourse'),
        ),
    ]
