# Generated by Django 3.1 on 2020-10-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_language_explore', '0004_student_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='xp',
            field=models.IntegerField(default=1),
        ),
    ]
