# Generated by Django 3.1 on 2020-09-07 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardannouncament',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
