# Generated by Django 3.1 on 2020-11-18 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_settings', '0002_basicuserprofile_location'),
        ('basic_feedback', '0002_feedbackcommentreply_feedback'),
        ('basic_voting_sys', '0007_bill_karma'),
        ('forum', '0006_auto_20201108_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_owner', to='profile_settings.basicuserprofile')),
                ('notified_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_user', to='profile_settings.basicuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ForumPostCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_notifications.notificationbase')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumcomment')),
            ],
        ),
        migrations.CreateModel(
            name='ForumCommentReplyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumcommentreply')),
                ('notification_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_notifications.notificationbase')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDevAnswerNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_dev_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_feedback.feedbackdevanswer')),
                ('notification_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_notifications.notificationbase')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCommentReplyNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_feedback.feedbackcommentreply')),
                ('notification_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_notifications.notificationbase')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCommentNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_feedback.feedbackcomment')),
                ('notification_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_notifications.notificationbase')),
            ],
        ),
        migrations.CreateModel(
            name='CongressBillVoteNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_voting_sys.billvote')),
                ('notification_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_notifications.notificationbase')),
            ],
        ),
    ]
