# Generated by Django 3.1 on 2020-11-19 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_notifications', '0002_notificationbase_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumcommentreplynotification',
            name='notification_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_comment_reply_notification', to='basic_notifications.notificationbase'),
        ),
        migrations.AlterField(
            model_name='forumpostcommentnotification',
            name='notification_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_post_comment_notification', to='basic_notifications.notificationbase'),
        ),
    ]
