# Generated by Django 3.1 on 2020-09-08 06:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLanguageCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('course_language', models.CharField(max_length=300)),
                ('course_speakers_language', models.CharField(max_length=300)),
            ],
        ),
    ]
