# Generated by Django 3.1 on 2020-09-08 09:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_authentication', '0004_teacheruserprofile_teacher_course'),
        ('teacher_language_explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherlanguagecourse',
            name='a0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherlanguagecourse',
            name='a1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherlanguagecourse',
            name='a2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherlanguagecourse',
            name='b1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherlanguagecourse',
            name='b2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherlanguagecourse',
            name='c1',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CourseStatusUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_language_explore.teacherlanguagecourse')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_authentication.teacheruserprofile')),
            ],
        ),
    ]
