# Generated by Django 3.1 on 2020-09-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_language_explore', '0002_auto_20200908_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestatusupdate',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
