# Generated by Django 3.1 on 2020-09-25 08:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_language_explore', '0003_auto_20200917_0628'),
        ('basic_vocab_container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicVocabErrorReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('error_report', models.TextField(default='...')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_language_explore.basiclanguagecourse')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_language_explore.student')),
                ('vocab_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basic_vocab_container.basicvocabularycontainer')),
            ],
        ),
    ]
