# Generated by Django 3.1 on 2020-11-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_vocab_container', '0003_studentvocabprogress_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicvocabularycontainer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='basic_vocab_container_audio/'),
        ),
    ]
