# Generated by Django 3.1 on 2020-09-02 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherApplication',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('course_language', models.CharField(max_length=300)),
                ('course_speakers_language', models.CharField(max_length=300)),
                ('native_language', models.CharField(max_length=200)),
                ('course_language_why_are_you_interested_text', models.TextField(max_length=1000)),
                ('speakers_language_why_are_you_interested_text', models.TextField(max_length=1000)),
                ('email', models.CharField(max_length=300)),
                ('older_than_13', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherUserProfile',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_permitted_to_signup', models.BooleanField(default=False)),
                ('native_language', models.CharField(blank=True, max_length=200, null=True)),
                ('course_language', models.CharField(blank=True, max_length=300, null=True)),
                ('course_speakers_language', models.CharField(blank=True, max_length=300, null=True)),
                ('first_name', models.CharField(blank=True, max_length=300, null=True)),
                ('last_name', models.CharField(blank=True, max_length=300, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=300, null=True)),
                ('occupation', models.CharField(blank=True, max_length=300, null=True)),
                ('email', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='teacher_profile_photo/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('personal_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('location', models.CharField(blank=True, max_length=1000, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
