# Generated by Django 3.1 on 2020-09-08 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_language_explore', '0001_initial'),
        ('teacher_authentication', '0003_remove_teacheruserprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacheruserprofile',
            name='teacher_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_language_explore.teacherlanguagecourse'),
        ),
    ]
