# Generated by Django 3.1 on 2020-08-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
