# Generated by Django 3.1 on 2020-11-08 12:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0002_basicuserprofile_location'),
        ('forum', '0005_forumpost_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ForumCommentReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('karma', models.IntegerField(default=0)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.forumcomment')),
                ('forum_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forum.forumpost')),
                ('reply_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
            ],
        ),
    ]
