# Generated by Django 3.1 on 2020-10-23 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_settings', '0002_basicuserprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonTrackRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
            ],
        ),
    ]
