# Generated by Django 3.1 on 2020-10-17 05:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile_settings', '0002_basicuserprofile_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, default='...', max_length=100, null=True)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackComment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('karma', models.IntegerField(default=0)),
                ('comment_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_feedback.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackDevAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_feedback.feedback')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackCommentReply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_feedback.feedbackcomment')),
                ('reply_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
            ],
        ),
    ]
