# Generated by Django 3.1 on 2021-01-15 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDictionary',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dictionary_language', models.CharField(blank=True, max_length=300, null=True)),
                ('dictionary_speakers_language', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
