# Generated by Django 3.1 on 2021-01-15 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_authentication', '0005_teacheruserprofile_is_permitted_to_push_prod'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherDictionaryWord',
            fields=[
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=50, null=True)),
                ('translation', models.CharField(blank=True, max_length=50, null=True)),
                ('dictionary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_dictionary.teacherdictionary')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher_authentication.teacheruserprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
