# Generated by Django 3.1 on 2021-01-17 09:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_authentication', '0005_teacheruserprofile_is_permitted_to_push_prod'),
        ('teacher_language_explore', '0003_coursestatusupdate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherReadingLesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('a0', 'a0'), ('a1', 'a1'), ('a2', 'a2'), ('b1', 'b1'), ('b2', 'b2'), ('c1', 'c1'), ('advanced', 'advanced')], default='a0', max_length=100)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_language_explore.teacherlanguagecourse')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_authentication.teacheruserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherReadingLessonSentence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='1', max_length=100)),
                ('question_prompt', models.CharField(max_length=2000)),
                ('answer', models.CharField(max_length=2000)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_reading_builder.teacherreadinglesson')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherReadingLessonSentenceTolerance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('tolerated_answer', models.CharField(max_length=2000)),
                ('lesson_sentence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_reading_builder.teacherreadinglessonsentence')),
            ],
        ),
    ]
