# Generated by Django 3.1 on 2020-09-09 10:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher_authentication', '0004_teacheruserprofile_teacher_course'),
        ('teacher_language_explore', '0003_coursestatusupdate_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherVocabularyContainer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('word', models.CharField(max_length=500)),
                ('level', models.CharField(choices=[('a0', 'a0'), ('a1', 'a1'), ('a2', 'a2'), ('b1', 'b2'), ('b2', 'b2'), ('c1', 'c1')], default='a0', max_length=10)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_language_explore.teacherlanguagecourse')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher_authentication.teacheruserprofile')),
            ],
        ),
    ]
