# Generated by Django 3.1 on 2020-09-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_vocab_container', '0002_auto_20200909_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachervocabularycontainer',
            name='level',
            field=models.CharField(choices=[('a0', 'a0'), ('a1', 'a1'), ('a2', 'a2'), ('b1', 'b1'), ('b2', 'b2'), ('c1', 'c1'), ('advanced', 'advanced')], default='a0', max_length=100),
        ),
    ]
