# Generated by Django 3.1 on 2020-09-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_vocab_container', '0003_auto_20200909_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachervocabularycontainer',
            name='word',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
