# Generated by Django 3.1 on 2020-09-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_vocab_container', '0004_auto_20200909_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachervocabularycontainer',
            name='word_translation',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
