# Generated by Django 3.1 on 2020-11-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_vocab_container', '0005_teachervocabularycontainer_word_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachervocabularycontainer',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='teacher_vocab_container_audio/'),
        ),
    ]
