# Generated by Django 3.1 on 2020-11-30 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher_vocab_container', '0006_teachervocabularycontainer_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachervocabularycontainer',
            name='audio',
        ),
    ]
