# Generated by Django 3.1 on 2020-10-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_voting_sys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='category',
            field=models.CharField(choices=[('new_feature', 'New Feature'), ('small_addition', 'Small Addition'), ('feature_complaint', 'Feature Complaint'), ('small_removal', 'Small Removal'), ('feature_removal', 'Feature Removal')], default='new_feature', max_length=100),
        ),
    ]
