# Generated by Django 3.1 on 2020-10-14 14:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0002_basicuserprofile_location'),
        ('basic_voting_sys', '0002_bill_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBillCreationDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
            ],
        ),
    ]
