# Generated by Django 3.1 on 2020-10-15 05:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile_settings', '0002_basicuserprofile_location'),
        ('basic_voting_sys', '0003_lastbillcreationdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillVote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('vote', models.CharField(choices=[('aye', 'aye'), ('neutral', 'neutral'), ('nay', 'nay')], default='neutral', max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_voting_sys.bill')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_settings.basicuserprofile')),
            ],
        ),
    ]
