# Generated by Django 3.1 on 2020-10-15 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_voting_sys', '0004_billvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillUpdateHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, default='...', null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_voting_sys.bill')),
            ],
        ),
    ]
