# Generated by Django 3.1 on 2020-10-15 12:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basic_voting_sys', '0005_billupdatehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillDeleteRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basic_voting_sys.bill')),
            ],
        ),
    ]
