# Generated by Django 3.1 on 2020-10-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_voting_sys', '0006_billdeleterequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='karma',
            field=models.IntegerField(default=0),
        ),
    ]
